sudo: false
language: ruby

install: sudo apt-get install openssl libssl-dev

script: bundle exec ruby spec/sig_spec.rb

rvm:
- 2.2
- 2.1
- rbx-2
- ruby-head
- jruby-9000

cache:
- bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9000
