sudo: false
language: ruby

install:
- sudo apt-get install openssl libssl-dev
- bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec ruby spec/sig_spec.rb

rvm:
- 2.2
- 2.1
- rbx-2.5.2
- ruby-head
- jruby-9000

cache:
- bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9000
